// Bowling Ball
// Written by: Brendan Lane | https://git.imbl.me/brendanlane

//
// Module Manager
//

// Utilities Imports
import { generateEmbed } from "./modules/utils/EmbedGenerator.js";

//
// Start of bot code
//

// Define major bot imports and variables
import Discord, { Message } from 'discord.js';

const client = new Discord.Client();
const escapeRegex = str => str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

import config from './config.js';
import secret_store from './secret_store.js';

// Initialization Code
client.on('ready', () => {
    console.log(`[Bowling Ball] Logged in as user ${client.user.tag}`);
    if(client.user.bot == true) {
        console.log('[Bowling Ball] This user is a bot user!');
    } else if(client.user.bot == false) {
        console.log('[Bowling Ball] This user is not a bot user!');
    } else {
        console.log('[Bowling Ball] Error: Cannot find out if user is a bot or not!');
	}
	client.user.setPresence({ activity: { name: 'with carpal tunnel', type: "STREAMING", url: "https://www.twitch.tv/smallkidwithgun" }});
});

// Command Parser
client.on('message', msg => {
	// Check list only on messages with the command
	if (!msg.content.startsWith(config.prefix) || msg.author.bot) return;

	// Define command variables
	const author = msg.author;

	const prefixRegex = new RegExp(`^(<@!?${client.user.id}>|${escapeRegex(config.prefix)})\\s*`);
	if (!prefixRegex.test(msg.content)) return;

	const [, matchedPrefix] = msg.content.match(prefixRegex);
	const args = msg.content.slice(matchedPrefix.length).trim().split(/ +/);
	const command = args.shift().toLowerCase();


	// Ping Command
    if (command === `ping`) {
		var startPing = Date.now();
		var pingMsg1 = generateEmbed("#cc3d32", ":ping_pong: Pong!", "Bowling Ball", "https://git.imbl.me/brendanlane/bowling-ball", "https://git.imbl.me/uploads/-/system/project/avatar/10/download__25_.jpg", "Getting ms... Please wait...", `Generated by ${author.username}#${author.discriminator}`, author.displayAvatarURL({ dynamic: true }));
		msg.channel.send(pingMsg1).then((sentMessage) => {
			var endPing = Date.now();
			var diffPing = endPing - startPing;
			var pingMsg2 = generateEmbed("#cc3d32", ":ping_pong: Pong!", "Bowling Ball", "https://git.imbl.me/brendanlane/bowling-ball", "https://git.imbl.me/uploads/-/system/project/avatar/10/download__25_.jpg", "Your ping was " + diffPing + "ms!", `Generated by ${author.username}#${author.discriminator}`, author.displayAvatarURL({ dynamic: true }));
			sentMessage.edit(pingMsg2);
		});
	// Profile Picture Command
    } else if (command === 'pfp') {
		if (!msg.mentions.users.size) {
			var pfpMsg = generateEmbed("#0a4f1b", `:bust_in_silhouette: ${author.username}'s avatar`, "Bowling Ball", "https://git.imbl.me/brendanlane/bowling-ball", "https://git.imbl.me/uploads/-/system/project/avatar/10/download__25_.jpg", "To get the avatar of others, just ping them", `Generated by ${author.username}#${author.discriminator}`, author.displayAvatarURL({ dynamic: true }));
			pfpMsg.setImage(author.displayAvatarURL({ format: "png", dynamic: true, size: 1024 }));
			return msg.channel.send(pfpMsg);
		}
	
		const avatarList = msg.mentions.users.map(user => {
			var pfpMsg = generateEmbed("#0a4f1b", `:bust_in_silhouette: ${user.username}'s avatar`, "Bowling Ball", "https://git.imbl.me/brendanlane/bowling-ball", "https://git.imbl.me/uploads/-/system/project/avatar/10/download__25_.jpg", "To get the avatar of others, just ping them", `Generated by ${author.username}#${author.discriminator}`, author.displayAvatarURL({ dynamic: true }));
			pfpMsg.setImage(user.displayAvatarURL({ format: "png", dynamic: true, size: 1024 }));
			return pfpMsg;
		});

		msg.channel.send(avatarList);
	// Help Command
	} else if (command === 'help') {
		var helpMsg = generateEmbed("#1f1e21", ":question: Bowling Ball - Help", "Bowling Ball", "https://git.imbl.me/brendanlane/bowling-ball", "https://git.imbl.me/uploads/-/system/project/avatar/10/download__25_.jpg", "Here you can find my commands!", `Generated by ${author.username}#${author.discriminator}`, author.displayAvatarURL({ dynamic: true }));
		helpMsg.addFields(
			{
				name: "Prefix",
				value: "My prefix is **bb!**, but you will be able to mention me Soon:tm:"
			},
			{
				name: "Fun",
				value: "bb!ping - bb!pfp <mentioned user>",
				inline: true
			}
		);

		msg.channel.send(helpMsg);
	}
});

// Login as the bot
client.login(secret_store.token);
